version: "1"

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456password
      MYSQL_DATABASE: healthnet
      MYSQL_USER: anhnv
      MYSQL_PASSWORD: 123456
    ports:
      - '3308:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

