version: "1"

networks:
  iam-service:
    driver: bridge

services:
  db:
    image: postgres:13.8
    restart: always
    environment:
      - POSTGRES_USER=anhnv
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=healthnet
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam-service


volumes:
  postgres_data:
    driver: local